name: 'Polyrific.Catapult.TaskProviders.EntityFramework'
type: 'DatabaseProvider'
author: 'Polyrific'
version: '1.0'
additional-configs:
  - name: StartupProjectName
    label: Startup Project Name
    type: string
    is-required: false
    is-secret: false
  - name: DatabaseProjectName
    label: Database Project Name
    type: string
    is-required: false
    is-secret: false
  - name: Configuration
    label: Configuration
    type: string
    is-required: false
    is-secret: false
  - name: ConnectionString
    label: ConnectionString
    type: string
    is-required: true
    is-secret: true
    is-input-masked: false